### PR TITLE
Change CS-fixer rules

### PR DESCRIPTION
**Pull request by imanghafoori1**
Change the cs fixer rules according to laravel core team recommendations.

https://gist.github.com/laravel-shift/cab527923ed2a109dda047b97d53c200

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Might be better to migrate to Laravel Pint in the end all together, no?

**Comment by imanghafoori1** [comment]
I think the integration between cs-fixer and the Phpstorm is preferable, pint has no integration with IDEs (yet).

**Comment by Cannonb4ll** [comment]
@SebastiaanKloos @Glennmen What do you think?

**Review by SebastiaanKloos — APPROVED** [review]
Cool thanks!

**Pull request merged**
