### PR TITLE
Moved logout button

### LINKED ISSUE #63: How to logout from LaraBug after logging in?

### PR DESCRIPTION
**Pull request by Glennmen**
Moved logout to side navigation:
CleanShot 2022-01-02 at 17 54 14

Fixes #63

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
@Glennmen maybe it would look a bit better if it’s placed a bit down in the sidebar. What do you think @Cannonb4ll

**Comment by Cannonb4ll** [comment]
I'd say add a separator in between, like below with the discord/sponsoring stuff. 

Also, a confirmation (vanilla would suffice: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) would be really welcome.

**Comment by Cannonb4ll** [comment]
@Glennmen Any update? 😍

**Comment by Glennmen** [comment]
@Cannonb4ll Update is I got lazy again 😂 
I will process the feedback asap.

I did try the `window.confirm()` last week but it didn't work for me 🤔 or at least it didn't work locally.

**Comment by SebastiaanKloos** [comment]
@Glennmen @Cannonb4ll I can work on this if you'd like🤓

**Comment by Glennmen** [comment]
@SebastiaanKloos Go ahead ;) I did take a quick look at it but it took me to much time

**Pull request merged**
