### PR TITLE
Added toggle to disable notifications on project

### PR DESCRIPTION
**Pull request by ricklambrechts**
- Added headless ui.
- Added toggle to disable notifications on project.
- Updated new and edit layout of project.

New project:
image

Edit project:
image

When notification toggle is off:
image

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
Hi @ricklambrechts I see you've added a real nice feature to LaraBug. Could you also create an option to toggle on / off the individual notification channels?

**Comment by Cannonb4ll** [comment]
Also it would be nice to drop the headless UI package, you can just use a checkbox as far as I am concerned.

**Comment by ricklambrechts** [comment]
@Cannonb4ll, I will change it to a checkbox.

@SebastiaanKloos, sure.

How do we want to call the fields?
Like this?
- slack_webhook_enabled
- discord_webhook_enabled
- custom_webhook_enabled

**Comment by ricklambrechts** [comment]
Also, should I rename the 'notifications_disabled' column to be 'notifications_enabled' with default true?

**Comment by SebastiaanKloos** [comment]
@ricklambrechts I'd prefer the `notifications_enabled` with default true. What do you think @Cannonb4ll?

**Comment by ricklambrechts** [comment]
Did the updates. Below is how it looks now.

image

**Comment by SebastiaanKloos** [comment]
> Did the updates. Below is how it looks now.
> 
> Also added validation. When you enable the "Call Slack Webhook", then the url must also be provided.
> 
> image

Could you also hide / show the notification inputs when the checkboxes are checked / unchecked?

**Comment by krekas** [comment]
I would say input should be below corresponding checkbox

**Comment by Cannonb4ll** [comment]
I agree.

**Comment by krekas** [comment]
For my eye perfect :)

**Comment by Cannonb4ll** [comment]
I am good with this, @SebastiaanKloos what do you think?

**Comment by SebastiaanKloos** [comment]
LGTM!

**Comment by Cannonb4ll** [comment]
Deployed and live 🥳

**Comment by SebastiaanKloos** [comment]
Thanks @ricklambrechts for your efforts!

**Pull request merged**
