### PR TITLE
Show request parameters

### PR DESCRIPTION
**Pull request by cbl**
This pr changes the `HEADERS` tab to `REQUEST`.

The request tab displays `headers` and `parameters`.
Bildschirmfoto 2021-05-06 um 11 32 22

### CODE REVIEW

**Comment by Glennmen** [comment]
Just curious, what happens if one of the parameters was a file upload? How will it be handled and displayed.

**Comment by Cannonb4ll** [comment]
@Glennmen It won't be sent over by the package thus it will never reach here. Let's say it will, there won't be any issue here either, it will be a JSON encoded value of UploadedFile:  https://laravel.com/api/7.x/Illuminate/Http/UploadedFile.html (not the file itself, but the details).

**Comment by Glennmen** [comment]
Yes it will be sent over 😉 
And my point is that if it is some "random" or encoded value then we might just better ignore it and not show it in the UI.

**Comment by Cannonb4ll** [comment]
Yes, but thats to be changed on the package side, not UI sided, this is ready to be merged.

**Comment by cbl** [comment]
I added a filter for the UploadFile value in https://github.com/LaraBug/LaraBug/pull/54

**Pull request merged**
