### PR TITLE
🔨  Install phpstan 

### PR DESCRIPTION
**Pull request by lloricode**
with level 5 for this time, and will do it until max level of 8

### CODE REVIEW

**Comment by lloricode** [comment]
since minimum php version is php 8.0, its recommended to enforce type hint, and this is will be enforce by `rule level 6` by phpstan https://phpstan.org/user-guide/rule-levels

**Comment by lloricode** [comment]
unused model detect on https://github.com/LaraBug/larabug-app/pull/59

**Comment by Cannonb4ll** [comment]
Awesome :) Will you also be running the solutions for these? Or what is your planning?

**Comment by lloricode** [comment]
> Awesome :) Will you also be running the solutions for these? Or what is your planning?

yes my plan is to fix all errors of every rule level until to max level (9), also phpstan ang larastan finally release stable version of it. 

will focusing on this sooner on weekends, thank you for trusting to this idea

**Comment by Cannonb4ll** [comment]
> config has `nova.php`, but no installed nova here, should we remove it?

Yes, remove this. I had Nova in LaraBug before to try it out but removed it after we went open source.

**Comment by lloricode** [comment]
from now on, we will start in rule level 1

**Comment by lloricode** [comment]
notice this after running `composer outdated --direct`

Screenshot from 2021-11-11 07-49-25

can i make another PR to upgrade this?

and also it has library that nothing to do with app `spatie/laravel-medialibrary`, can we remove this?
we should remove packages that nothing to do with the app

**Comment by lloricode** [comment]
we can move `spatie/laravel-ray` to --dev level requirements in composer.json, and add [`spatie/x-ray`](https://github.com/spatie/x-ray) to check if is there a usage of tool before commit/push it in version control

**Comment by Cannonb4ll** [comment]
> notice this after running `composer outdated --direct`
> 
> Screenshot from 2021-11-11 07-49-25
> 
> can i make another PR to upgrade this?
> 
> and also it has library that nothing to do with app `spatie/laravel-medialibrary`, can we remove this? we should remove packages that nothing to do with the app

Yes, and yes!

**Comment by Cannonb4ll** [comment]
> we can move `spatie/laravel-ray` to --dev level requirements in composer.json, and add [`spatie/x-ray`](https://github.com/spatie/x-ray) to check if is there a usage of tool before commit/push it in version control

Agree!

**Comment by lloricode** [comment]
replace `carbon()` to `now()` to make sure can easily adopt laravel for mock time testing

**Comment by lloricode** [comment]
This time will apply PSR 12

**Comment by lloricode** [comment]
notice that too many custom attributes being used, much better if this is just regular functions, too difficult to debug with many custom attributes

sample `getRouteUrlAttribute()` to `getRouteUrl()` to minimize laravel magic call

what do you think?

**Comment by lloricode** [comment]
is `app/Http/Resources/Api/SponsorResource.php` model is being used? dont see any table in database after fresh migrate

**Comment by lloricode** [comment]
confuse this line
https://github.com/LaraBug/larabug-app/blob/695e16b118acc7ca223ef332dcca2ebe634ddc4c/app/Console/Commands/CheckExpiredPlans.php#L45

test suite success but class `UserPlanExpired` not exist, this need to be notified in failing test

**Comment by Cannonb4ll** [comment]
> notice that too many custom attributes being used, much better if this is just regular functions, too difficult to debug with many custom attributes
> 
> sample `getRouteUrlAttribute()` to `getRouteUrl()` to minimize laravel magic call
> 
> what do you think?

Agree, would not mind this change.

**Comment by Cannonb4ll** [comment]
> is `\App\Models\Sponsor` model is being used? dont see any table in database after fresh migrate

Yes, this is certainly being used, however, it doesn't uses the database or eloquent. It uses `Sushi` (check trait on model).

https://github.com/calebporzio/sushi

It is being used to display sponsors on https://www.larabug.com/larabug-is-free

You can leave this model as it is.

**Comment by Cannonb4ll** [comment]
> confuse this line
> 
> https://github.com/LaraBug/larabug-app/blob/695e16b118acc7ca223ef332dcca2ebe634ddc4c/app/Console/Commands/CheckExpiredPlans.php#L45
> 
> test suite success but class `UserPlanExpired` not exist, this need to be notified in failing test

This logic can completely be removed, it is not being used anymore as LaraBug is free now.

**Comment by lloricode** [comment]
thanks for the response, will continue later 💯

**Comment by lloricode** [comment]
hi, will focusing this on December vacation

**Comment by Cannonb4ll** [comment]
Hey @lloricode!

What's the status of this one? ❤️

**Comment by lloricode** [comment]
> Hey @lloricode!
> 
> What's the status of this one? ❤️

Hi, sorry for the waiting, we have urgent project since before christmas so i was not able to do it on spare time, and still discover more about phpstan in our project so this will be easy to apply on larabug site, thank you for the waiting, will visit this in few weeks

**Pull request closed without merging**
