### PR TITLE
Add dev dependency roave/security-advisories

### PR DESCRIPTION
**Pull request by lloricode**
then sort dev dependencies

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Why is this package `roave/security-advisories` added?

**Comment by lloricode** [comment]
> Why is this package `roave/security-advisories` added?

Hi is just check security advisories to prevent installing vulnerable version of packages

**Comment by SebastiaanKloos** [comment]
@lloricode First of all, many thanks for your effort and dedication!

We try to keep the composer.json file as minimalistic as possible. We review every change to this file carefully so I don't see why we should add this package in LaraBug by default.

What do you think @Cannonb4ll

**Review by Cannonb4ll — COMMENTED** [review]
I agree with @SebastiaanKloos, there's no real need for this package to be added as of now.

**Comment by lloricode** [comment]
its ok since we usually update/upgrade the packages

**Pull request closed without merging**
